[nebula_api]
user_api_token = 1234567890
authorization_header =
user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15'

[nebula_filters]
; If the variable is set to `false`, the filter is disabled, otherwise it is enabled and is applied to search. Example: `category_search = originals`
category_search = false
include_nebula_first = false
include_nebula_plus = true
include_nebula_originals = true
include_regular_videos = false
; If the variable is set to `false`, the filter is disabled, otherwise it is enabled and is only these channels are searched. Example: `channels_to_parse = jetlag`
channels_to_parse =

[downloader]
download_path = ./output
check_interval_hours = 1
